export const metadata = {
  title: "Terms & Conditions | Free QR Code Generator",
  description: "Terms and conditions for using our free QR code generator tool."
};

export default function TermsConditions() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50 px-4 py-16">
      
      <section className="max-w-4xl mx-auto bg-white/80 backdrop-blur-xl shadow-2xl rounded-3xl p-8 md:p-12 border border-gray-100">
        
        {/* Title */}
        <h1 className="text-4xl md:text-5xl font-extrabold text-center bg-gradient-to-r from-slate-700 to-blue-600 bg-clip-text text-transparent mb-8">
          Terms & Conditions
        </h1>

        <div className="w-24 h-1 bg-gradient-to-r from-blue-500 to-indigo-500 mx-auto rounded-full mb-10"></div>

        {/* Content */}
        <div className="space-y-8 text-gray-700 leading-relaxed text-lg">

          <p>
            By accessing or using our <strong>Free QR Code Generator</strong>, you agree to be bound 
            by these Terms & Conditions. Please read them carefully.
          </p>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-3">Use of Service</h2>
            <p>
              You may use our QR code generator for personal, educational, or commercial purposes. 
              You agree not to misuse the service or engage in any activity that could harm the website or other users.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-3">Intellectual Property</h2>
            <p>
              All content, designs, and software on this website are the property of the website owner 
              and are protected by applicable copyright laws. You may not reproduce, distribute, or modify 
              any part of the service without prior written permission.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-3">Disclaimer</h2>
            <p>
              The QR codes generated by this service are provided “as-is”. We do not guarantee their 
              accuracy, reliability, or security. Use the service at your own risk.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-3">Limitation of Liability</h2>
            <p>
              In no event shall the website owner be liable for any direct, indirect, incidental, 
              or consequential damages arising from the use of this service.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-semibold text-gray-800 mb-3">Changes to Terms</h2>
            <p>
              We reserve the right to update or modify these Terms & Conditions at any time without prior notice. 
              Please check this page periodically for updates.
            </p>
          </div>

          <p className="text-sm text-gray-500 pt-6 border-t">
            By using our website, you acknowledge that you have read, understood, and agree to these Terms & Conditions.
          </p>

        </div>

      </section>
    </main>
  );
}
